//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PresentationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PresentationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exam.PresentationResource", typeof(PresentationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem lehet üres a mező!.
        /// </summary>
        internal static string DataManagementForm_Add_Error {
            get {
                return ResourceManager.GetString("DataManagementForm_Add_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeres hozzáadás.
        /// </summary>
        internal static string DataManagementForm_Add_Success {
            get {
                return ResourceManager.GetString("DataManagementForm_Add_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hozzáad.
        /// </summary>
        internal static string DataManagementForm_AddButton {
            get {
                return ResourceManager.GetString("DataManagementForm_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az Író már létezik!.
        /// </summary>
        internal static string DataManagementForm_AuthorAlreadyExists {
            get {
                return ResourceManager.GetString("DataManagementForm_AuthorAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Könyv szerzője:.
        /// </summary>
        internal static string DataManagementForm_AuthorNameLabel {
            get {
                return ResourceManager.GetString("DataManagementForm_AuthorNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A könyv már létezik!.
        /// </summary>
        internal static string DataManagementForm_BookAlreadyExists {
            get {
                return ResourceManager.GetString("DataManagementForm_BookAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Könyv címe:.
        /// </summary>
        internal static string DataManagementForm_BookTitleLabel {
            get {
                return ResourceManager.GetString("DataManagementForm_BookTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilépés.
        /// </summary>
        internal static string DataManagementForm_CloseButton {
            get {
                return ResourceManager.GetString("DataManagementForm_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} a helyes válaszaid száma: {1}..
        /// </summary>
        internal static string GameForm_CheckButton_Evaluation_1 {
            get {
                return ResourceManager.GetString("GameForm_CheckButton_Evaluation_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2:0.##}%-ot értél el!.
        /// </summary>
        internal static string GameForm_CheckButton_Evaluation_2 {
            get {
                return ResourceManager.GetString("GameForm_CheckButton_Evaluation_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellenőrzés.
        /// </summary>
        internal static string GameForm_CheckButton_Text {
            get {
                return ResourceManager.GetString("GameForm_CheckButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilépés.
        /// </summary>
        internal static string GameForm_CloseButton_Text {
            get {
                return ResourceManager.GetString("GameForm_CloseButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérem a neved.
        /// </summary>
        internal static string GameForm_InputBox_Text {
            get {
                return ResourceManager.GetString("GameForm_InputBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ki írta: {0}?.
        /// </summary>
        internal static string GameForm_QuestionLabel {
            get {
                return ResourceManager.GetString("GameForm_QuestionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melyik szerző írta ezt a könyvet?.
        /// </summary>
        internal static string GameForm_QuestionLabel_Default {
            get {
                return ResourceManager.GetString("GameForm_QuestionLabel_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mégse.
        /// </summary>
        internal static string InputBox_Cancel {
            get {
                return ResourceManager.GetString("InputBox_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string InputBox_Ok {
            get {
                return ResourceManager.GetString("InputBox_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adat feltöltés.
        /// </summary>
        internal static string MainForm_Menu_AddData {
            get {
                return ResourceManager.GetString("MainForm_Menu_AddData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új játék.
        /// </summary>
        internal static string MainForm_Menu_NewGame {
            get {
                return ResourceManager.GetString("MainForm_Menu_NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haladó (25 kérdés).
        /// </summary>
        internal static string MainForm_Menu_NewGame_Advanced {
            get {
                return ResourceManager.GetString("MainForm_Menu_NewGame_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kezdő (10 kérdés).
        /// </summary>
        internal static string MainForm_Menu_NewGame_Beginner {
            get {
                return ResourceManager.GetString("MainForm_Menu_NewGame_Beginner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egyedi.
        /// </summary>
        internal static string MainForm_Menu_NewGame_Custom {
            get {
                return ResourceManager.GetString("MainForm_Menu_NewGame_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem pozítív egész számot adtál meg!.
        /// </summary>
        internal static string MainForm_Menu_NewGame_Custom_Error {
            get {
                return ResourceManager.GetString("MainForm_Menu_NewGame_Custom_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mennyi kérdést szeretnél?.
        /// </summary>
        internal static string MainForm_Menu_NewGame_Custom_Questions {
            get {
                return ResourceManager.GetString("MainForm_Menu_NewGame_Custom_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statisztika.
        /// </summary>
        internal static string MainForm_Menu_Statistics {
            get {
                return ResourceManager.GetString("MainForm_Menu_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilépés.
        /// </summary>
        internal static string Statisticsform_CloseButton_Text {
            get {
                return ResourceManager.GetString("Statisticsform_CloseButton_Text", resourceCulture);
            }
        }
    }
}
